# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c76f9d8050ac3c78daa0e5b03703f9cc1741e45363b14c3e2b67fb7a33d595755f80c0874ece1f07d1cd8b0952807f1f51eb0b9053fdbeed2fdc4ef268c9d4b4

test:
  secret_key_base: 827b6bd8244392b38ec504045b96675c9e42ae6c206891168b831a65ca76f74c0cfc950ba383e4033285a6da2ee216618bca6028f49d60acc7e3c856621d3deb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
